name: Deploy to GitHub - Prod Stage

permissions:
  contents: write

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Get version from package.json
        id: package
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
  
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: vscode-json-v${{ steps.package.outputs.version }}
          files: json-${{ steps.package.outputs.version }}.vsix
